[package]
name = "moriartys_challenge"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tfhe = "0.2.4"
concrete-csprng = "0.3.0"
rand = "0.8.5"
sha2 = "0.10.6"
hex = "0.4.3"